In [2]:
import torch

In [3]:
x = torch.tensor(0)
x.shape

torch.Size([])

In [4]:
x.size()

torch.Size([])

In [9]:
x = torch.tensor([0, 1, 2, 3])
print(x.shape)
print(x.t())

torch.Size([4])
tensor([0, 1, 2, 3])


In [8]:
x = torch.tensor([
    [0, 1],
    [2, 3]
])
print(x.shape)
print(x.size())
print(x.t())

torch.Size([2, 2])
torch.Size([2, 2])
tensor([[0, 2],
        [1, 3]])


In [13]:
x = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])

print(x.t())
print(x.size())

tensor([[0, 2, 4],
        [1, 3, 5]])
torch.Size([3, 2])


In [26]:
w = torch.tensor([2, 3])

print("(n, m) @ (m, ) 계산 시 PyTorch에서 벡터처럼 취급. 계산 후 벡터용 차원 제거 후 반환")
print(x.shape, "@", w.shape)
#
(x @ w).shape

(n, m) @ (m, ) 계산 시 PyTorch에서 벡터처럼 취급. 계산 후 벡터용 차원 제거 후 반환
torch.Size([3, 2]) @ torch.Size([2])


torch.Size([3])

In [20]:
# w = torch.tensor([[2, 3]])
#
# x @ w

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

In [19]:
x * 10

tensor([[ 0, 10],
        [20, 30],
        [40, 50]])

In [24]:
w = torch.tensor([[2], [3]])

print(x.shape, "@", w.shape)

(x @ w).shape

torch.Size([3, 2]) @ torch.Size([2, 1])


torch.Size([3, 1])

In [27]:
w = torch.tensor([[2], [3]])

print(w.shape, "@", x.shape)

# (w @ x).shape

torch.Size([2, 1]) @ torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 3x2)

In [15]:
w.size()

torch.Size([2, 1])

In [28]:
x[:, 0:1]

tensor([[0],
        [2],
        [4]])

In [31]:
x = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ],
    [
        [9, 10],
        [11, 12]
    ]
])
x.shape

torch.Size([3, 2, 2])

In [33]:
x.flatten()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
torch.randn(20, 3, 64, 64).shape

torch.Size([20, 3, 64, 64])

In [36]:
torch.randn(1)

tensor([0.9535])

In [38]:
torch.randn(20, 3, 64, 64).flatten().shape

torch.Size([245760])

In [41]:
x2 =torch.randn(20, 3, 64, 64).reshape(20, 12288)
x2.shape

torch.Size([20, 12288])

In [42]:
x = torch.randn(20, 3, 64, 64)
x2 = x.reshape(x.shape[0], -1)
x2.shape

torch.Size([20, 12288])

In [44]:
print(x.shape)
x2 = torch.flatten(x, start_dim=1)
x2.shape

torch.Size([20, 3, 64, 64])


torch.Size([20, 12288])

In [45]:
x2 = x.view(20, 12288)

In [46]:
x = torch.randn(2, 3)
x

tensor([[ 0.7078,  0.8380, -0.1789],
        [-2.0392, -0.2995, -0.8802]])

In [49]:
x.t()

tensor([[ 0.7078, -2.0392],
        [ 0.8380, -0.2995],
        [-0.1789, -0.8802]])

In [50]:
type(x.t())

torch.Tensor

In [47]:
# x.t().view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [51]:
x_view = x.view(-1)
x_view

tensor([ 0.7078,  0.8380, -0.1789, -2.0392, -0.2995, -0.8802])

In [52]:
x[0, 0] = 20
x_view

tensor([20.0000,  0.8380, -0.1789, -2.0392, -0.2995, -0.8802])

In [53]:
model = torch.nn.Linear(12288, 10)

In [54]:
model.weight.shape

torch.Size([10, 12288])

In [55]:
model.weight

Parameter containing:
tensor([[ 0.0067, -0.0088,  0.0050,  ...,  0.0026,  0.0044, -0.0049],
        [-0.0052, -0.0063,  0.0059,  ...,  0.0026, -0.0025,  0.0072],
        [-0.0002, -0.0025, -0.0067,  ..., -0.0064,  0.0003,  0.0041],
        ...,
        [-0.0053, -0.0038, -0.0011,  ...,  0.0057, -0.0065, -0.0063],
        [-0.0085,  0.0056, -0.0082,  ...,  0.0030,  0.0048,  0.0019],
        [-0.0016,  0.0078,  0.0021,  ..., -0.0086,  0.0053, -0.0039]],
       requires_grad=True)

In [56]:
model.bias

Parameter containing:
tensor([ 0.0044, -0.0079,  0.0020, -0.0005, -0.0014, -0.0050,  0.0036,  0.0035,
         0.0087, -0.0068], requires_grad=True)

In [57]:
model.bias.shape

torch.Size([10])

In [58]:
torch.nn.Linear(1, 12).bias.shape

torch.Size([12])

In [60]:
x = torch.rand(20, 12288)

In [61]:
y_pred = model(x)
y_pred.shape

torch.Size([20, 10])

In [67]:
print(list(model.parameters())[0].shape)
print(list(model.parameters())[1].shape)

torch.Size([10, 12288])
torch.Size([10])


In [ ]:
layer1 = torch.nn.Linear(3, 2)
layer2 = torch.nn.Linear(2, 3)

In [69]:
relu = torch.nn.ReLU()

In [70]:
x = torch.tensor([-1, -2, 0, 2, 3])

relu(x)

tensor([0, 0, 0, 2, 3])

In [72]:
model = torch.nn.Sequential(
    torch.nn.Linear(5, 8),
    torch.nn.ReLU(),
    torch.nn.Linear(8, 3),
)

In [73]:
from torch import nn

In [74]:
model = nn.Sequential(
    nn.Linear(5, 8),
    nn.ReLU(),
    nn.Linear(8, 3)
)

In [75]:
print(model)

Sequential(
  (0): Linear(in_features=5, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=3, bias=True)
)


In [78]:
isinstance(model, nn.Module) and isinstance(model, nn.Sequential)

False

In [80]:
print(type(model))
print(type(model[0]))
print(type(model[1]))
print(type(model[2]))

<class 'torch.nn.modules.container.Sequential'>
<class 'torch.nn.modules.linear.Linear'>
<class 'torch.nn.modules.activation.ReLU'>
<class 'torch.nn.modules.linear.Linear'>


In [81]:
first = model[0]

print(first.weight.shape)
print(first.weight)

torch.Size([8, 5])
Parameter containing:
tensor([[ 0.2728, -0.1803, -0.3140, -0.0952, -0.2053],
        [ 0.0465,  0.4052,  0.1001, -0.4222, -0.0150],
        [ 0.2302,  0.3084, -0.3132, -0.2506, -0.2479],
        [ 0.0440, -0.3420, -0.3434,  0.1177, -0.0540],
        [ 0.0687,  0.1313, -0.2379, -0.3450, -0.3913],
        [-0.0065,  0.1035,  0.1003,  0.1000, -0.2415],
        [ 0.3113,  0.2253, -0.1800,  0.0871, -0.3917],
        [ 0.0273,  0.1394, -0.4284,  0.3648,  0.0321]], requires_grad=True)


In [87]:
second = model[1]

# print(second.weight.shape)
# print(second.weight)
print(type(second))
for p in second.parameters():
    print("param")
    print(p.shape)

<class 'torch.nn.modules.activation.ReLU'>


In [82]:
for p in model.parameters():
    print(p.shape)

torch.Size([8, 5])
torch.Size([8])
torch.Size([3, 8])
torch.Size([3])


In [88]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

In [90]:
print(model.named_parameters())
for name, p in model.named_parameters():
    print(name, p.shape)

<generator object Module.named_parameters at 0x00000138E7AF2440>
0.weight torch.Size([8, 5])
0.bias torch.Size([8])
2.weight torch.Size([3, 8])
2.bias torch.Size([3])


In [94]:
x = torch.randn(4, 5)

y = model(x)
print(model)

x, y

Sequential(
  (0): Linear(in_features=5, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=3, bias=True)
)


(tensor([[ 0.4211,  1.0043,  1.1240, -0.5038, -0.0946],
         [-1.0418,  0.9259,  2.0550, -1.2262,  1.2698],
         [-1.0968, -1.2548,  0.5407, -0.9629,  0.6686],
         [ 0.1635,  0.3801, -1.0232, -0.4193,  0.5569]]),
 tensor([[-0.2852,  0.0956, -0.4494],
         [-0.3475,  0.0254, -0.4146],
         [-0.1713, -0.2437, -0.1706],
         [-0.2750,  0.1412, -0.2683]], grad_fn=<AddmmBackward0>))

In [97]:
h1 = model[0](x)
h2 = model[1](h1)
y = model[2](h2)

print("h1:", h1)
print("h2:", h2)
print("y:", y)

h1: tensor([[ 0.0688,  0.8870, -0.1446, -1.1231,  0.4289, -0.2293,  0.1944, -0.6940],
        [-0.8198,  1.1650, -0.9544, -1.6391, -0.1880, -0.5361, -1.0434, -1.3635],
        [ 0.1322,  0.0251, -1.0821, -0.3124,  0.0266, -0.7420, -1.0210, -0.9433],
        [ 0.6435,  0.3616,  0.0935, -0.2089,  0.5560, -0.6566,  0.1123,  0.1836]],
       grad_fn=<AddmmBackward0>)
h2: tensor([[0.0688, 0.8870, 0.0000, 0.0000, 0.4289, 0.0000, 0.1944, 0.0000],
        [0.0000, 1.1650, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1322, 0.0251, 0.0000, 0.0000, 0.0266, 0.0000, 0.0000, 0.0000],
        [0.6435, 0.3616, 0.0935, 0.0000, 0.5560, 0.0000, 0.1123, 0.1836]],
       grad_fn=<ReluBackward0>)
y: tensor([[-0.2852,  0.0956, -0.4494],
        [-0.3475,  0.0254, -0.4146],
        [-0.1713, -0.2437, -0.1706],
        [-0.2750,  0.1412, -0.2683]], grad_fn=<AddmmBackward0>)


In [ ]:
y2 = model(x)

# 허용 오차 범위 안에서 서로 같은지
print(torch.allclose(y, y2))


In [104]:
model = nn.Sequential(
    nn.Linear(4, 6),
    nn.ReLU(),
    nn.Linear(6, 2)
)

print(model)

for m in model:
    print(f"\n --- {m} --- \n")
    try:
        print(m.weight.shape)
        print(m.bias.shape)
    except:
        print("no such attr")

print(f"\n --- model parameters --- \n")
for name, p in model.named_parameters():
    print(name, p)

Sequential(
  (0): Linear(in_features=4, out_features=6, bias=True)
  (1): ReLU()
  (2): Linear(in_features=6, out_features=2, bias=True)
)

 --- Linear(in_features=4, out_features=6, bias=True) --- 

torch.Size([6, 4])
torch.Size([6])

 --- ReLU() --- 

no such attr

 --- Linear(in_features=6, out_features=2, bias=True) --- 

torch.Size([2, 6])
torch.Size([2])

 --- model parameters --- 

0.weight Parameter containing:
tensor([[-0.2050, -0.3807,  0.2352,  0.1624],
        [-0.1173, -0.0674, -0.1583,  0.4921],
        [ 0.2648,  0.3734, -0.1301,  0.1196],
        [-0.3351,  0.3948, -0.1045,  0.4408],
        [-0.0235,  0.2608,  0.1770, -0.4438],
        [-0.2404,  0.3890, -0.1322, -0.1560]], requires_grad=True)
0.bias Parameter containing:
tensor([-0.2541,  0.4158, -0.3836,  0.1212, -0.1585,  0.3753],
       requires_grad=True)
2.weight Parameter containing:
tensor([[ 0.1802,  0.0045, -0.0741, -0.3040, -0.1950,  0.1639],
        [-0.2160, -0.0381,  0.1578,  0.0451, -0.3675, -0.1123]],


In [105]:
x = torch.randn(10, 4)

# 최종 형태는 반드시 (10, 2)
y = model(x)

# 4, 6
h1 = model[0](x)
# ReLU
h2 = model[1](h1)
# 6, 2
y2 = model[2](h2)

print(y)
print(y2)

tensor([[-0.1728, -0.4379],
        [-0.4816, -0.9327],
        [-0.2572, -0.3650],
        [-0.4329, -0.3225],
        [-0.3813, -0.2416],
        [-0.3037, -0.4376],
        [-0.1734, -0.4470],
        [-0.3948, -0.6027],
        [-0.2694, -0.4181],
        [-0.2559, -0.3180]], grad_fn=<AddmmBackward0>)
tensor([[-0.1728, -0.4379],
        [-0.4816, -0.9327],
        [-0.2572, -0.3650],
        [-0.4329, -0.3225],
        [-0.3813, -0.2416],
        [-0.3037, -0.4376],
        [-0.1734, -0.4470],
        [-0.3948, -0.6027],
        [-0.2694, -0.4181],
        [-0.2559, -0.3180]], grad_fn=<AddmmBackward0>)
