In [2]:
import numpy as np

In [5]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr = np.arange(0, 49, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.reshape(np.arange(1, 10), (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr = np.arange(1, 25).reshape(2, 3, 4)

print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3, 4)
3
24


In [24]:
arr = np.array([[10, 20, 30], [40, 50, 60]]).reshape(1, -1)
print(arr)
np.array([[10, 20, 30], [40, 50, 60]]).flatten()

[[10 20 30 40 50 60]]


array([10, 20, 30, 40, 50, 60])

In [28]:
arr = np.arange(10, 91, 10).reshape(3, 3)
arr[1, 1]

np.int64(50)

In [ ]:
arr[1]

array([50, 60])

In [ ]:
arr[:, 2] # (3, )
arr[:, 1:2] #(3, 1)

array([[20],
       [50],
       [80]])

In [39]:
arr[1:, 1:]

array([[50, 60],
       [80, 90]])

In [42]:
arr = np.array([10, 25, 30, 45, 50, 15])

arr[arr >= 30]

array([30, 45, 50])

In [44]:
arr = np.arange(1, 21)

arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
arr = np.array([10, 20, 30, 40, 100])

arr[arr > arr.mean()]

array([100])

In [48]:
arr = np.array([1, 2, 3, 4, 5])

arr + 10

array([11, 12, 13, 14, 15])

In [50]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [53]:
a = np.arange(1, 4)
b = np.arange(10, 40, 10)

a + b

array([11, 22, 33])

In [57]:
arr = np.reshape(np.arange(1, 10), (3, 3))

arr += [10, 20, 30]

arr

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [59]:
arr = np.reshape(np.arange(1, 10), (3, 3))

print(arr.sum())
print(arr.sum(axis=1))
print(arr.sum(axis=0))

45
[ 6 15 24]
[12 15 18]


In [62]:
arr = np.array([
    [80, 90, 100],
    [70, 60, 50],
    [30, 40, 50]
])

print(arr.mean())
print(arr.mean(axis=1))
print(arr.mean(axis=0))

63.333333333333336
[90. 60. 40.]
[60.         63.33333333 66.66666667]


In [64]:
arr = np.array([
    [3, 7, 2],
    [9, 1, 5],
    [4, 8, 6]
])

print(np.max(arr, axis=0))

[9 8 6]


In [66]:
print(np.min(arr, axis=0))

[3 1 2]


In [70]:
arr = np.array([10, 20, 30, 40 ,100])

print(arr.mean())
print(np.median(arr))
print(arr.var())
print(arr.std())

40.0
30.0
1000.0
31.622776601683793


In [72]:
arr = np.array([5, 10, 15, 20, 25, 30, 100])
print(np.quantile(arr, 0.25))
print(np.quantile(arr, 0.5))
print(np.quantile(arr, 0.75))

12.5
20.0
27.5


In [106]:
arr = np.array([5, 10, 15, 20, 25, 30, 100])

q1 = np.quantile(arr, 0.25)
q3 = np.quantile(arr, 0.75)

iqr = q3 - q1

print(iqr)

lower = q1 - 1.5* iqr
upper = q3 + 1.5* iqr

print(lower)
print(upper)

15.0
-10.0
50.0


In [107]:
scores = np.array([
    [80, 90, 100],
    [70, 85, 90],
    [60, 75, 70],
    [95, 90, 85],
    [50, 60, 65]
])

print(scores.mean(axis=1))

[90.         81.66666667 68.33333333 90.         58.33333333]


In [78]:
scores.mean(axis=0)

array([71., 80., 82.])

In [191]:
student_mean_score = scores.mean(axis=1)
print(scores[student_mean_score>80])

[[ 95  85  75]
 [ 60 100  90]
 [ 70  80  95]]


In [110]:
print(student_mean_score.max())
print(np.where(student_mean_score == student_mean_score.max())[0])

print(np.argmax(student_mean_score))

90.0
[0 3]
0


In [88]:
# [fixed_acidity, volatile_acidity, alcohol, quality]
wine = np.array([
    [7.4, 0.70, 9.4, 5],
    [7.8, 0.88, 9.8, 5],
    [7.9, 0.76, 9.8, 6],
    [11.2, 0.28, 9.8, 6],
    [7.4, 0.70, 9.4, 5],
    [7.4, 0.66, 9.4, 5],
    [7.9, 0.60, 9.4, 5],
    [7.3, 0.65, 10.0, 7]
])

print(wine[wine[:, 3]>=6])

[[ 7.9   0.76  9.8   6.  ]
 [11.2   0.28  9.8   6.  ]
 [ 7.3   0.65 10.    7.  ]]


In [90]:
print(wine[:, 2].mean())

9.625


In [99]:
print(wine[wine[:, 3]>=6][:, 2].mean())

9.866666666666667


In [101]:
good_wine_alcohol_mean = wine[wine[:, 3]>=6][:, 2].mean()

print(wine[wine[:, 2]>good_wine_alcohol_mean])

[[ 7.3   0.65 10.    7.  ]]


In [104]:
print(wine[:, : -1])

[[ 7.4   0.7   9.4 ]
 [ 7.8   0.88  9.8 ]
 [ 7.9   0.76  9.8 ]
 [11.2   0.28  9.8 ]
 [ 7.4   0.7   9.4 ]
 [ 7.4   0.66  9.4 ]
 [ 7.9   0.6   9.4 ]
 [ 7.3   0.65 10.  ]]


In [111]:
wine_feature = wine[:, :-1]

print(wine_feature.mean())
print(wine_feature.std())

6.105416666666667
3.9750880275018927


In [126]:
arr = np.array([40, 10, 70, 30, 90, 20])

print(arr.max())
print(arr.argmax())
print(arr.argmin())
print(np.argsort(arr))
print(np.where(arr>=30)[0])
print(arr[arr>=30])

90
4
1
[1 5 3 0 2 4]
[0 2 3 4]
[40 70 30 90]


In [180]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5, -1])

print(np.unique(arr))

[-1  1  2  3  4  5]


In [181]:
print(np.unique(arr))
print([int((arr==i).sum()) for i in np.unique(arr)]) # 이거 아닌거같은데

print(np.unique(arr, return_counts=True, return_index=True, return_inverse=True))

[-1  1  2  3  4  5]
[1, 1, 2, 3, 2, 1]
(array([-1,  1,  2,  3,  4,  5]), array([9, 0, 1, 3, 6, 8]), array([1, 2, 2, 3, 3, 3, 4, 4, 5, 0]), array([1, 1, 2, 3, 2, 1]))


In [136]:
scores = np.array([80, 45, 60, 30, 90])
print(np.where(scores>=50, "pass", "fail"))

['pass' 'fail' 'pass' 'fail' 'pass']


In [140]:
arr = np.array([-10, 20, 50, 120, 200])

print(arr.clip(0, 100))

[  0  20  50 100 100]


In [182]:
arr = np.array([10, np.nan, 30, np.nan, 50])
print(np.where(np.isnan(arr))) # 이거 왜 튜플로 나오는거지
print(np.nansum(arr))
print(np.nanmean(arr))

(array([1, 3]),)
90.0
30.0


In [145]:
arr = np.array([10, 20, 30, 40])

print(arr.cumsum())

[ 10  30  60 100]


In [147]:
arr = np.array([100, 120, 90, 150, 200])

print(np.diff(arr)) # 가끔씩 ndarray에는 없는데 np로만 수행 가능한 함수가 있는 이유가 뭐지



[ 20 -30  60  50]


In [185]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
print(a[0])

print(np.concat([a, b], axis=0))

print(np.concatenate([a, b], axis=0))

print(np.vstack([a, b]))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [160]:
print(np.concat([a, b], axis=1))

[[1 2 3 4 5 6]]


In [162]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# 11. 백분위 말하는건가
print(np.quantile(arr, 0.75))

62.5


In [190]:
arr = np.array([3, 5, 7, 0, 10, -1])

print((arr < 0).sum() >= 0)

print(np.all(arr >= 0))
print(np.all(np.array([0, 1])))

True
False
False


In [169]:
arr = np.array([3, 5, -1, 0, 10])

print((arr < 0).sum() > 0)

True


In [175]:
scores = np.array([
    [80, 90, 70],
    [95, 85, 75],
    [60, 100, 90],
    [70, 80, 95]
])

# class_max = scores.max(axis=0)
# print(class_max)

print(np.argmax(scores, axis=0))
print(np.argmax(scores, axis=1))

[1 2 3]
[1 0 1 2]
