In [1]:
import torch

x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

In [2]:
x.shape

torch.Size([2, 3])

In [3]:
type(x.shape)

torch.Size

In [4]:
x.shape.count(12)

0

In [5]:
isinstance(x.shape, torch.Tensor)

False

In [6]:
x.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [7]:
x.dtype

torch.int64

In [8]:
x[0]

tensor([1, 2, 3])

In [9]:
x[0, 0].item()

1

In [10]:
x[0, 0]

tensor(1)

In [11]:
type(x[0])

torch.Tensor

In [12]:
x.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [13]:
x.flatten().unsqueeze(0).shape

torch.Size([1, 6])

In [14]:
x.flatten().unsqueeze(0).unsqueeze(2).shape

torch.Size([1, 6, 1])

In [15]:
x.flatten().unsqueeze(0).unsqueeze(2)

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])

In [16]:
x = torch.tensor([
    [
        [
            [11, 12, 13],
            [14, 15, 16],
        ],
        [
            [21, 22, 23],
            [24, 25, 26],
        ]
    ],
    [
        [
            [31, 32, 33],
            [34, 35, 36],
        ],
        [
            [41, 42, 43],
            [44, 45, 46],
        ]
    ]
])

In [17]:
x.shape

torch.Size([2, 2, 2, 3])

In [18]:
x.flatten()

tensor([11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26, 31, 32, 33, 34, 35, 36,
        41, 42, 43, 44, 45, 46])

In [19]:
x.squeeze(2).shape

torch.Size([2, 2, 2, 3])

In [20]:
x

tensor([[[[11, 12, 13],
          [14, 15, 16]],

         [[21, 22, 23],
          [24, 25, 26]]],


        [[[31, 32, 33],
          [34, 35, 36]],

         [[41, 42, 43],
          [44, 45, 46]]]])

In [21]:
x.unsqueeze(3)

tensor([[[[[11, 12, 13]],

          [[14, 15, 16]]],


         [[[21, 22, 23]],

          [[24, 25, 26]]]],



        [[[[31, 32, 33]],

          [[34, 35, 36]]],


         [[[41, 42, 43]],

          [[44, 45, 46]]]]])

In [22]:
x.squeeze(([1])).shape

torch.Size([2, 2, 2, 3])

In [23]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

y = torch.tensor([
    [3, 4, 5]
])

x * y

tensor([[ 3,  8, 15],
        [12, 20, 30]])

In [24]:
try:
    x @ y
except Exception as e:
    print(e)

mat1 and mat2 shapes cannot be multiplied (2x3 and 1x3)


In [25]:
y @ x.T

tensor([[26, 62]])

In [26]:
x + y

tensor([[ 4,  6,  8],
        [ 7,  9, 11]])

In [27]:
x / 4

tensor([[0.2500, 0.5000, 0.7500],
        [1.0000, 1.2500, 1.5000]])

In [28]:
type(x + 2), x + 2

(torch.Tensor,
 tensor([[3, 4, 5],
         [6, 7, 8]]))

In [29]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x.argmax()

tensor(5)

In [31]:
x.argmax(dim=1) # 2 예상 -> [2, 2] = 각 행마다의 최대위치

tensor([2, 2])

In [32]:
z = torch.tensor([
    [
        [1, 5, 3],
        [4, 2, 6],
        # [9, 9, 9]
    ],
    [
        # [9, 9, 9],
        [2, 6, 4],
        [5, 3, 7]
    ]
])

z.argmax(dim=1) # [5, 5]?

tensor([[1, 0, 1],
        [1, 0, 1]])

In [33]:
z.argmax(dim=0)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
z.argmax(dim=2)

tensor([[1, 2],
        [1, 2]])