In [1]:
import torch
import torch.nn as nn

x = torch.tensor([
    [
        [1.0, 2.0, 3.0, 4.0],
        [2.0, 1.0, 0.0, 1.0],
        [0.5, 1.5, 2.5, 3.5]
    ]
])

print(x.shape)

torch.Size([1, 3, 4])


In [2]:
linear1 = nn.Linear(
    in_features=4,
    out_features=8
)

hidden = linear1(x)

print(hidden.shape)

torch.Size([1, 3, 8])


In [4]:
[(n, p) for n, p in linear1.named_parameters()]

[('weight',
  Parameter containing:
  tensor([[-0.0449,  0.0219,  0.1659, -0.4368],
          [ 0.0529, -0.4725,  0.3512, -0.1789],
          [-0.4961,  0.4703, -0.3657,  0.4174],
          [-0.2802,  0.3926,  0.0462, -0.3754],
          [-0.3507, -0.4785,  0.4465,  0.1071],
          [ 0.4322,  0.3262,  0.1975,  0.3471],
          [-0.3723, -0.1579, -0.3802, -0.4396],
          [ 0.4177,  0.0831, -0.3416, -0.3672]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([-0.3412, -0.0928, -0.3777,  0.0919, -0.0121,  0.4415,  0.4912,  0.3779],
         requires_grad=True))]

In [5]:
activation = nn.ReLU()

hidden2 = activation(hidden)

print(hidden2.shape)

torch.Size([1, 3, 8])


In [7]:
print(hidden)
print(hidden2)

tensor([[[-1.5919, -0.6468,  0.6392, -0.7663,  0.4479,  3.5069, -3.0960,
          -1.5318],
         [-0.8460, -0.6383, -0.4822, -0.4513, -1.0849,  1.9792, -0.8508,
           0.9292],
         [-1.4449, -0.5231,  0.6263, -0.6579,  0.5858,  2.8554, -2.4210,
          -1.4278]]], grad_fn=<ViewBackward0>)
tensor([[[0.0000, 0.0000, 0.6392, 0.0000, 0.4479, 3.5069, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.9792, 0.0000, 0.9292],
         [0.0000, 0.0000, 0.6263, 0.0000, 0.5858, 2.8554, 0.0000, 0.0000]]],
       grad_fn=<ReluBackward0>)


In [8]:
linear2 =  nn.Linear(8, 4)

output = linear2(hidden2)

print(output.shape)

torch.Size([1, 3, 4])


In [10]:
class FFN(nn.Module):
    def __init__(self, dim_model, dim_ff):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(dim_model, dim_ff),
            nn.GELU(),
            nn.Linear(dim_ff, dim_model)
        )

    def forward(self, x):
        return self.net(x)

In [9]:
token = [x[:, i, :] for i in range(3)]

print(token[0].shape)

torch.Size([1, 4])


In [11]:
ffn = FFN(4, 8)
o1 = ffn(token[0])
o2 = ffn(token[1])
o3 = ffn(token[2])

print(o1)
print(o2)
print(o3)

tensor([[ 0.2934,  0.1022, -0.2942, -0.4483]], grad_fn=<AddmmBackward0>)
tensor([[-0.0735,  0.0576, -0.3745, -0.6240]], grad_fn=<AddmmBackward0>)
tensor([[ 0.2440,  0.0628, -0.2338, -0.4075]], grad_fn=<AddmmBackward0>)


In [13]:
print(ffn(x))

tensor([[[ 0.2934,  0.1022, -0.2942, -0.4483],
         [-0.0735,  0.0576, -0.3745, -0.6240],
         [ 0.2440,  0.0628, -0.2338, -0.4075]]], grad_fn=<ViewBackward0>)
