In [5]:
import numpy as np

A = np.array([
  [1, 4, 8],
  [2, 7, 9],
  [3, 9, 10]
])

# det(A) = 70 + 108 + 144 - 81 - 80 - 168 = -7
# np.linalg.det(A) = np.float64(-6.999999999999999)
# 스빈 행렬 (여인수 행렬 전치)
# [-11, 32, -20]
# [7, -14, 7]
# [-3, 3, -1]

A_inv = np.linalg.inv(A)
A_inv

array([[ 1.57142857, -4.57142857,  2.85714286],
       [-1.        ,  2.        , -1.        ],
       [ 0.42857143, -0.42857143,  0.14285714]])

<img src="https://blog.kakaocdn.net/dna/bVCshc/btsHR1wY4Ey/AAAAAAAAAAAAAAAAAAAAADApGAK5Zvmux-kIg3c3Oc0CUPE80ibo6dW-zqDnFZvy/img.png?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1782831599&allow_ip=&allow_referer=&signature=TQ6%2FcmSqcmhck9RDfyPJ9o%2Bp9Jc%3D" width="400px">

In [29]:
# 높은행렬 (10, 4) 무작위로 만들기
T = np.random.randint(1, 100, size=(10, 4))
T_t = T.T

print(L := np.linalg.inv(T_t @ T)@T_t)

k = np.round(L@T, 2)
k = np.where(np.isclose(k, np.round(k)), np.round(k), k)
# k = np.trunc((np.linalg.inv(L)@T_t@T) * 100)/100
# print(k*100)
print(k)

print(np.round(T@L, 2))

[[ 6.29319004e-03  5.14297581e-04  3.45400240e-03  1.96614253e-03
  -4.53520359e-03 -2.64419812e-03 -8.70056134e-04 -4.19675591e-03
  -3.19669689e-03  4.68032041e-03]
 [ 1.60522177e-03 -2.08346510e-03  8.29213582e-04  1.47169536e-04
   8.61641633e-03  1.17042902e-03  2.67115496e-03  1.07346736e-03
   1.72808409e-03 -6.60007750e-03]
 [-5.34748774e-03  5.68702410e-03 -3.86037484e-03  8.37132587e-04
  -1.45409012e-03 -1.35451575e-03  1.74594183e-03  5.57268637e-03
  -1.52051596e-03  1.62814014e-03]
 [-1.71847307e-03 -2.36617675e-03  1.08925703e-03  2.52176508e-05
   5.04313032e-04  4.15304152e-03 -1.59728711e-03  5.55684366e-04
   4.81183916e-03  1.58397322e-03]]
[[ 1. -0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]
[[ 0.56 -0.06  0.32  0.18  0.11 -0.12  0.08 -0.24 -0.13  0.04]
 [-0.06  0.39 -0.09  0.18 -0.04 -0.16  0.18  0.28 -0.18  0.16]
 [ 0.32 -0.09  0.28  0.17  0.08  0.09  0.   -0.1   0.11  0.16]
 [ 0.18  0.18  0.17  0.27  0.11  0.02  0.13  0.15  0.04  0.22]
 [

In [13]:
# 높은행렬 (10, 4) 무작위로 만들기
T = np.array([
  [1, 0],
  [0, 1],
  [1, 1]
])
T_t = T.T

print(L := T_t @ T)

np.linalg.inv(L)@T_t@T

[[2 1]
 [1 2]]


array([[1., 0.],
       [0., 1.]])

In [ ]:
T = np.array([
  [1, 0, 3, 3+1],
  [0, 1, 4, 4+1],
  [1, 1, 8, 8+1]
])
try:
  print(np.linalg.inv(T))
except:
  print("np.linalg.inv(T) 실패")
finally:
  print(f"\n --- 의사 역행렬 --- \n")
  print(A_p := np.linalg.pinv(T))

np.round(T@A_p, 2)

np.linalg.inv(T) 실패

 --- 의사 역행렬 --- 

[[ 4.   3.  -3. ]
 [ 4.   5.  -4. ]
 [-0.5 -0.5  0.5]
 [-0.5 -0.5  0.5]]


array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [48]:
T = np.array([
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])

np.linalg.inv(T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])