In [ ]:
import numpy as np

arr = np.array([
  [
    [1, 2, 3],
    [1,23,4]
  ],
  [
    [1,2,3],
    [1,23,4]
  ]])

axis=0

arr.shape

np.sum(arr, axis=1)

# [
#   [
#     [6, 28]
#   ],
#   [
#     [6, 28]
#   ],
#   [
#     [6, 28]
#   ]
# ]
# [
#   [3 6 9],
#   [3 69 12]
# ]

array([[ 2, 25,  7],
       [ 2, 25,  7],
       [ 2, 25,  7]])

In [8]:
import pandas as pd

T1 = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])

T2 = T1*2

T2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [9]:
T1*T2

array([[ 2,  8],
       [18, 32],
       [50, 72]])

In [11]:
# (3, 2)
T1 = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])

T1*np.array([
  [0, 0], 
  [1, 2]
]) # (2, 2)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [ ]:
T1 = np.array([
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [7],
  [8],
  [9], # -> 
  [10], 
])
# 차원 축소
# (10, 100) @ (1, 30) -> (10, 30)
T2 = np.array([
  [3, 6],
])

(T1@T2)

array([[ 3,  6],
       [ 6, 12],
       [ 9, 18],
       [12, 24],
       [15, 30],
       [18, 36],
       [21, 42],
       [24, 48],
       [27, 54],
       [30, 60]])

In [ ]:
# 검정 - 