# 랜덤 포레스트 실습
> 랜덤포레스트 복습용 연습 코드입니다.

우선 분류 데이터를 위한 `sklearn.datasets.make_classification`, 검증 데이터 분할을 위한 `sklearn.model_selection.train_test_split`, `sklearn.ensemble.RandomForestClassifier`, `sklearn.metrics`의 `accuracy_score`과 `confusion_matrix`를 가져오도록 하겠습니다.

In [2]:
# 분류 데이터셋 생성
from sklearn.datasets import make_classification
# 검증데이터 분할 전략
from sklearn.model_selection import train_test_split
# 랜덤 포레스트 분류기 클래스
from sklearn.ensemble import RandomForestClassifier
# 정확도 점수 및 혼동행렬
from sklearn.metrics import accuracy_score, confusion_matrix

## 1. 예제 데이터 생성하기

In [ ]:
X, y = make_classification(
    # (500, 5) shape의 행렬 생성하기
    n_samples=500,
    n_features=5,

    # 실제로 유용한 정보를 가진 feature 3개
    n_informative=3,
    # 선형결합으로 만들어진 중복 feature
    n_redundant=0,

    # 시드 고정
    random_state=42
)

In [4]:
# 데이터셋 확인
print("X shape:", X.shape)
print("y shape:", y.shape)

print("X[:3]:\n", X[:3])
print("y[:10]:", y[:10])

X shape: (500, 5)
y shape: (500,)
X[:3]:
 [[-1.8306329  -0.09533956 -0.65407568  0.72405061 -0.18131925]
 [ 0.26028051  0.08015108 -0.41346516 -1.27331422  1.48260887]
 [-1.37961816  0.09874375 -0.97165673 -0.07279847 -1.57955514]]
y[:10]: [0 1 1 1 1 0 0 1 1 1]


# 2. train / test 데이터 분리

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    # y클래스의 비율을 전체 데이터의 비율과 최대한 유지해서 나누게 하는 것
    # 층촤 추출법
    stratify=y
)

In [7]:
print("\ntrain:", X_train.shape, y_train.mean())
print("test :", X_test.shape, y_train.mean())


train: (400, 5) 0.505
test : (100, 5) 0.505


# 3. Random Forest 모델 객체 생성

In [8]:
model = RandomForestClassifier(
    n_estimators=100, # 트리 개수를 100개로 설정
    max_depth=None, # 최대 깊이를 제한하지 않음 = 과적합 가능
    random_state=42
)

In [10]:
print("\nmodel:")
print(model)


model:
RandomForestClassifier(random_state=42)


# 4. 학습 후 예측해보기

In [15]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_pred[:10], y_pred.shape, type(y_pred)

(array([1, 0, 0, 1, 1, 1, 1, 0, 0, 0]), (100,), numpy.ndarray)

# 5. 평가

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("\naccuracy:", accuracy)

print("\nconfusion matrix:")
print(confusion_matrix(y_test, y_pred))

# 5-1. 평가 지표 결과

정확도: 92%

|        |  예측 F   |  예측 T   |
|:------:|:---------:|:---------:|
| 실제 F | TN - 0.46 | FP - 0.04 |
| 실제 T | FN - 0.04 | TP - 0.46 |

> `Recall`/`TPR` 0.92 (TP / TP + FN)

> `Precision` 0.92 (TP / TP + FP)

# 6. 평가 이후에 생기는 데이터들

In [22]:
print(type(model.estimators_))
print(len(model.estimators_))
print(model.estimators_[:5])

<class 'list'>
100
[DecisionTreeClassifier(max_features='sqrt', random_state=1608637542), DecisionTreeClassifier(max_features='sqrt', random_state=1273642419), DecisionTreeClassifier(max_features='sqrt', random_state=1935803228), DecisionTreeClassifier(max_features='sqrt', random_state=787846414), DecisionTreeClassifier(max_features='sqrt', random_state=996406378)]
