# 3. 다중 선형 회귀
다중 선형 회귀(Multiple Linear Regression)는 여러 개의 독립 변수(입력 변수)를 사용해 하나의 종속 변수(출력 변수)를 예측하는 통계 및 머신러닝 기법입니다.

단순 선형 회귀가 하나의 독립 변수와 하나의 종속 변수 간의 선형 관계를 설명하는 반면, 다중 선형 회귀는 두 개 이상의 입력 변수가 출력 변수에 어떻게 영향을 미치는지를 분석합니다.

이 관계는 수식으로 표현되며, 예를 들어 Y=W1X1+W2X2+...+WnXn+b와 같이 나타납니다. 여기서 Y는 예측 값, X1,X2,...Xn ​은 입력 변수, W1,W2,...Wn ​은 각 변수의 가중치, b는 절편입니다.

다중 선형 회귀는 입력 변수들이 독립적이고, 종속 변수와 선형 관계를 가진다는 가정 하에 작동하며, 주로 경제학, 의료, 마케팅 등 다양한 분야에서 복합적인 요인의 영향을 분석하고 예측하는 데 사용됩니다.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

X_train = torch.FloatTensor([
        [50, 55, 60],   # 학생 1
        [60, 65, 70],   # 학생 2
        [70, 72, 75],   # 학생 3
        [75, 80, 78],   # 학생 4
        [80, 82, 85],   # 학생 5
        [88, 90, 92],   # 학생 6
        [95, 96, 98]   # 학생 7
   	]).to(device)

y_train = torch.FloatTensor([
    [58],
    [67],
    [73],
    [78],
    [83],
    [90],
    [97],
]).to(device)

print(X_train, X_train.shape)
print(y_train, y_train.shape)

model = nn.Linear(3, 1).to(device)
print(model)

# optimizer = optim.SGD(model.parameters(), lr=0.00001)
optimizer = optim.Adam(model.parameters(), lr=0.01)

loss_fn = nn.MSELoss()

epochs = 1000

for epoch in range(epochs + 1):

    y_pred = model(X_train)

    loss = loss_fn(y_pred, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'Epoch: {epoch}/{epochs}, Loss: {loss.item():.6f}')

print("\n모델 파라미터:")
for param in model.parameters():
    print(param)

x_test = torch.FloatTensor([[90, 91, 92]]).to(device)
y_pred = model(x_test)
print(f"\n새로운 입력 데이터 {x_test.tolist()}의 예측 결과: {y_pred.item():.4f}")

device: cuda
tensor([[50., 55., 60.],
        [60., 65., 70.],
        [70., 72., 75.],
        [75., 80., 78.],
        [80., 82., 85.],
        [88., 90., 92.],
        [95., 96., 98.]], device='cuda:0') torch.Size([7, 3])
tensor([[58.],
        [67.],
        [73.],
        [78.],
        [83.],
        [90.],
        [97.]], device='cuda:0') torch.Size([7, 1])
Linear(in_features=3, out_features=1, bias=True)
Epoch: 0/1000, Loss: 20378.107422
Epoch: 100/1000, Loss: 10.318493
Epoch: 200/1000, Loss: 0.850620
Epoch: 300/1000, Loss: 0.847520
Epoch: 400/1000, Loss: 0.843836
Epoch: 500/1000, Loss: 0.839584
Epoch: 600/1000, Loss: 0.834786
Epoch: 700/1000, Loss: 0.829471
Epoch: 800/1000, Loss: 0.823663
Epoch: 900/1000, Loss: 0.817366
Epoch: 1000/1000, Loss: 0.810600

모델 파라미터:
Parameter containing:
tensor([[0.1326, 0.5944, 0.2673]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.9218], device='cuda:0', requires_grad=True)

새로운 입력 데이터 [[90.0, 91.0, 92.0]]의 예측 결과: 91.5471

In [4]:
print(X_train.shape, X_train)
print(y_train.shape, y_train)

torch.Size([7, 3]) tensor([[50., 55., 60.],
        [60., 65., 70.],
        [70., 72., 75.],
        [75., 80., 78.],
        [80., 82., 85.],
        [88., 90., 92.],
        [95., 96., 98.]], device='cuda:0')
torch.Size([7, 1]) tensor([[58.],
        [67.],
        [73.],
        [78.],
        [83.],
        [90.],
        [97.]], device='cuda:0')


In [6]:
# y = w1x1 + w2x2 + w3x3 + b
model = nn.Linear(3, 1).to(device)
print(model)

Linear(in_features=3, out_features=1, bias=True)


In [7]:
loss_fn = torch.nn.MSELoss()

# Adam
Adam(Adaptive Moment Estimation)은 경사하강법(Gradient Descent)을 개선한 최적화 알고리즘으로, 머신러닝과 딥러닝 모델 학습에서 널리 사용됩니다. Adam은 SGD(Stochastic Gradient Descent)의 단점을 보완하기 위해 개발되었으며, 각 가중치(Weight)와 편향(Bias)마다 다른 학습률(Learning Rate)을 적용해 더욱 효율적이고 안정적으로 최적화를 수행합니다.

Adam은 모든 가중치에 똑같은 크기의 학습률을 그대로 적용하지 않습니다. 각 가중치의 기울기 상태를 확인하면서 실제 업데이트 크기를 자동으로 조절합니다. 따라서 코드에 lr=0.01을 지정했더라도 모든 가중치가 항상 정확히 0.01만큼 수정되는 것은 아닙니다.



# 1. Adam은 이전 기울기의 방향을 기억합니다.

Adam은 현재 계산된 기울기만 사용하는 것이 아니라 이전 학습에서 계산된 기울기의 흐름도 함께 사용합니다.

이를 **1차 모멘트**라고 합니다. 최근까지 가중치가 어느 방향으로 계속 움직이고 있었는지를 기억하는 것입니다. 기울기가 여러 번 같은 방향으로 나타나면 Adam은 그 방향이 손실을 줄이는 데 도움이 되는 방향이라고 판단합니다.



# 2. Adam은 기울기의 크기도 기억합니다.

Adam은 기울기의 방향뿐만 아니라 기울기가 얼마나 컸는지도 기억합니다. 이를 **2차 모멘트**라고 합니다. 기울기가 지나치게 큰 가중치는 업데이트 크기를 줄이고, 기울기가 상대적으로 작은 가중치는 적절히 업데이트되도록 조절합니다.



# 3. Adam이라고 항상 가장 좋은 것은 아닙니다

Adam은 편리하고 빠르게 학습되는 경우가 많지만 항상 최고의 선택은 아닙니다. 입력 데이터를 정규화하거나 표준화하면 학습이 더 안정적으로 진행됩니다.  단순한 문제의 경우 SGD로도 충분히 학습할 수 있습니다. Adam을 사용한 것은 입력값 크기에 따른 학습 불안정을 어느 정도 줄이는 데 도움이 됩니다. 그러나 Adam이 데이터 전처리를 완전히 대신해 주는 것은 아닙니다.

In [8]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [9]:
epochs = 1000

for epoch in range(1, epochs + 1):

    y_pred = model(X_train)

    loss = loss_fn(y_pred, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'Epoch: {epoch}/{epochs}, Loss: {loss.item():.6f}')

Epoch: 100/1000, Loss: 1.236914
Epoch: 200/1000, Loss: 0.165164
Epoch: 300/1000, Loss: 0.164987
Epoch: 400/1000, Loss: 0.164786
Epoch: 500/1000, Loss: 0.164556
Epoch: 600/1000, Loss: 0.164295
Epoch: 700/1000, Loss: 0.164009
Epoch: 800/1000, Loss: 0.163698
Epoch: 900/1000, Loss: 0.163364
Epoch: 1000/1000, Loss: 0.163008


In [10]:
print("\n모델 파라미터:")

for param in model.parameters():
    print(param)


모델 파라미터:
Parameter containing:
tensor([[0.0237, 0.3625, 0.5938]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.9701], device='cuda:0', requires_grad=True)


In [12]:
x_test = torch.FloatTensor([[90, 91, 92]]).to(device)
y_pred = model(x_test)

print(f"\n새로운 입력 데이터 {x_test.tolist()}의 예측 결과: {y_pred.item():.4f}")


새로운 입력 데이터 [[90.0, 91.0, 92.0]]의 예측 결과: 90.7201
