In [3]:
import pandas as pd
import numpy as np

In [4]:
X = np.array([
    [1.0, 5.0, 12],
    [1.5, 6.0, 10],
    [2.0, 5.5, 9],
    [2.5, 6.5, 8],
    [3.0, 6.0, 7],
    [3.5, 7.0, 6],
    [4.0, 6.5, 5],
    [4.5, 7.5, 5],
    [5.0, 7.0, 4],
    [5.5, 8.0, 3],
    [6.0, 7.5, 3],
    [6.5, 8.0, 2],
    [2.0, 4.5, 11],
    [3.0, 5.0, 9],
    [4.0, 5.5, 7],
    [5.0, 6.0, 5],
    [6.0, 6.5, 4],
    [7.0, 7.0, 3],
    [7.5, 7.5, 2],
    [8.0, 8.0, 1],
])

y = np.array([
    0, 0, 0, 0, 0,
    0, 0, 1, 1, 1,
    1, 1, 0, 0, 0,
    1, 1, 1, 1, 1
])

In [13]:
print(X.shape)
print(X.ndim)
print(y.shape)
print(np.mean(X))
print(X.mean())
print("feature mean", np.mean(X, axis=0))
print("feature min", np.min(X, axis=0))
print("feature max", np.max(X, axis=0))
print("feature std", np.std(X, axis=0))

(20, 3)
2
(20,)
5.566666666666666
5.566666666666666
feature mean [4.375 6.525 5.8  ]
feature min [1.  4.5 1. ]
feature max [ 8.  8. 12.]
feature std [2.01168462 1.04253297 3.12409987]


In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    stratify=y # split의 결과의 train과 test의 비율이 맞게 y라벨을 기준으로 설정해주기
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(15, 3)
(5, 3)
(15,)
(5,)


In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:3])
print(X_test_scaled[:3])

[[ 0.03377723  0.93541435 -0.21873932]
 [ 0.28710646 -0.56793014 -0.21873932]
 [ 0.28710646  0.43429952 -0.5468483 ]]
[[-0.72621046 -0.56793014  0.43747864]
 [-1.23286892 -2.07127462  1.74991456]
 [ 1.30042338  0.43429952 -0.87495728]]


In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_scaled, y_train)

print("coef_", model.coef_)
print("intercept_", model.intercept_)
print("classes_", model.classes_)

coef_ [[ 1.10962274  0.6445045  -0.85147532]]
intercept_ [0.1192945]
classes_ [0 1]


In [34]:
pred = model.predict(X_test_scaled)
print("predict", model.predict(X_test_scaled))
print("proba + argmax", model.predict_proba(X_test_scaled).argmax(axis=1))
print("score", model.score(X_test_scaled, y_test))

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay

# 정확도
print("acc score:", accuracy_score(y_test, pred))

# 혼동행렬 및 f1score, r2 등
print("confusion matrix [tn, fp, fn, tp] \n", confusion_matrix(y_test, pred))

#
print("classification_report\n", classification_report(y_test, pred))

predict [0 0 1 1 0]
proba + argmax [0 0 1 1 0]
score 1.0
acc score: 1.0
confusion matrix [tn, fp, fn, tp] 
 [[3 0]
 [0 2]]
classification_report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

