# **1. 자연어**
자연어는 인간이 일상적으로 의사소통에 사용하는 언어로, 말과 글을 통해 표현되는 언어를 말합니다. 자연어는 문법, 어휘, 맥락, 뉘앙스 등 복잡한 요소들로 이루어져 있어 규칙적인 구조와 함께 다양한 변형이 가능합니다. 컴퓨터 과학에서는 이러한 자연어를 이해하고 처리하기 위해 자연어 처리(NLP, Natural Language Processing) 기술이 사용되며, 이를 통해 텍스트 분석, 번역, 음성 인식, 챗봇과 같은 다양한 응용이 가능합니다. 자연어는 인간의 사고와 문화적 배경을 반영하므로, 이를 다루는 기술은 인문학적 이해와 기술적 접근이 결합되어야 합니다.

# **2. 자연어 처리**
자연어 처리는(Natural Language Processing, NLP) 컴퓨터가 인간의 언어를 이해하고 처리하며 생성할 수 있도록 돕는 인공지능 기술 분야입니다. 이를 통해 텍스트나 음성 데이터를 분석하고, 번역, 요약, 감정 분석, 질의응답, 음성인식 등 다양한 작업을 수행할 수 있습니다. 자연어 처리는 언어학, 컴퓨터 과학, 인공지능의 융합으로 이루어지며, 형태소 분석, 구문 분석, 의미 분석 등 여러 단계를 포함합니다. 최근에는 딥러닝 기술과 대규모 언어 모델의 발전으로 자연어 처리 성능이 크게 향상되어 챗봇, 검색 엔진, 추천 시스템과 같은 실생활 응용에서 널리 사용되고 있습니다.

- 텍스트 분류
- 감정 분석
- 문서 요약
- 기계 번역
- 질의 응답
- 정보 검색
- 챗봇
- 문장 생성
- RAG
- LLM 기반 Agent

> 최근에는 자연어 처리 기술이 이미지, 음성, 영상 등의 데이터와 결합하면서 Multimodal AI 확장

### Corpus
Corpus(말뭉치)는 자연어 처리에서 분석하거나 학습하기 위해 수집한 전체 텍스트 데이터의 집합


### Document
- Corpus를 구성하는 각각의 텍스트 데이터
- Document라고 해서 반드시 긴 문서를 의미하는 것은 아님
- 예) 뉴스 기사 하나, 리뷰 하나, 댓글 하나, 문장 하나 등

# **3. Tokenization**
- 텍스트를 모델이 처리할 수 있는 작은 단위인 Token으로 나누는 과정
- [토큰 계산](https://platform.openai.com/tokenizer)

### 토큰
- 토큰은 모델이 처리하는 텍스트의 작은 단위
- 하나의 토큰은 단어, 부분적인 단어, 공백이나 구두점일 수 있음
- 토큰은 반드시 단어 하나를 의미하지는 않음

### Vocabulary
- Vocabulary는 Tokenizer가 사용하는 토큰들의 집합
- 각 토큰에는 고유한 정수 ID가 할당됨
- 정수 ID 자체는 언어적인 의미가 전혀 없음

### 허깅 페이스
허깅 페이스(Hugging Face)는 자연어 처리뿐 아니라 이미지, 음성, 영상, 멀티모달 모델을 공유하고 사용하는 데 필요한 여러 도구와 서비스를 제공하는 AI 생태계이자 회사 이름

In [15]:
import torch

In [16]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
elif torch.backends.mps.is_available():
    DEVICE = torch.device('mps')
elif torch.xpu.is_available():
    DEVICE = torch.device('xpu')
else:
    DEVICE = torch.device('cpu')

print(DEVICE)

cuda


In [17]:
text = "나는 자연어를 공부한다"
tokens = text.split()
# tokens
vocab = {"<PAD>":0, "<UNK>":1, "나는":2, "자연어를":3, "공부한다":4}
token_ids = [vocab.get(token, vocab['<UNK>']) for token in tokens]
# token_ids

input_ids = torch.tensor(token_ids, dtype=torch.long)

print("원문: ", text)
print("Token: ", tokens)
print("Token ID: ", token_ids)
print("PyTorch Tensor: ", input_ids)
print("dtype: ", input_ids.dtype)

원문:  나는 자연어를 공부한다
Token:  ['나는', '자연어를', '공부한다']
Token ID:  [2, 3, 4]
PyTorch Tensor:  tensor([2, 3, 4])
dtype:  torch.int64


In [18]:
from transformers import AutoTokenizer

C:\LANG_CHAIN_2026\2026-05-19_KDT_lang_chain\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [19]:
# 허깅 페이스 허브의 "klue/bert-base" Repository에서 Tokenizer 설정과 Voca를 불러옴
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

In [20]:
text = "자연어 처리를 공부합니다."
tokens = tokenizer.tokenize(text)
print("Token: ", tokens)
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print("token ID: ", token_ids)

Token:  ['자연', '##어', '처리', '##를', '공부', '##합니다', '.']
token ID:  [3941, 2051, 4211, 2138, 4244, 11800, 18]


In [92]:
tokenizer.vocab_size

32000

In [21]:
print("Vocabulary 크기: ", tokenizer.vocab_size)
print("[PAD] ID: ", tokenizer.pad_token_type_id)
print("[UNK] ID: ", tokenizer.unk_token_id)
print("[CLS] ID: ", tokenizer.cls_token_id)
print("[SEP] ID: ", tokenizer.sep_token_id)

Vocabulary 크기:  32000
[PAD] ID:  0
[UNK] ID:  1
[CLS] ID:  2
[SEP] ID:  3


In [99]:
print(f"token_id: 0:, {tokenizer.convert_ids_to_tokens(0)}")
print(f"token_id: 1:, {tokenizer.convert_ids_to_tokens(1)}")
print(f"token_id: 2:, {tokenizer.convert_ids_to_tokens(2)}")
print(f"token_id: 3:, {tokenizer.convert_ids_to_tokens(3)}")

token_id: 0:, [PAD]
token_id: 1:, [UNK]
token_id: 2:, [CLS]
token_id: 3:, [SEP]


In [110]:
text = "hello i'm hurwan홯ㅇㅎㅇ"
tokenizer.tokenize(text)

['he', '##ll', '##o', 'i', "'", 'm', '[UNK]']

In [107]:
output = tokenizer(text)
output.keys()

KeysView({'input_ids': [2, 14712, 10211, 2036, 76, 11, 80, 75, 4704, 2175, 3947, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

In [106]:
output["input_ids"]

[2, 14712, 10211, 2036, 76, 11, 80, 75, 4704, 2175, 3947, 3]

In [108]:
output["token_type_ids"]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [109]:
output["attention_mask"]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

### OOV
- OOV(Out-Of-Vacabulary)는 Voca에 존재하지 않는 Token이 입력되는 문제
- 과거의 단어 단위 Voca에서는 처음 보는 단어를 \<UNK\>와 같은 Unknown Token으로 처리하는 경우가 많았음
- 현대 NLP에서는 Subword Tokenization을 이용하여 이 문제를 크게 줄임

In [22]:
vocab = {"<PAD>":0, "<UNK>":1, "나는":2, "파이토치를":3, "공부한다":4}
tokens = {"나는", "트랜스포머를", "공부한다"}
token_ids = [vocab.get(token, vocab['<UNK>']) for token in tokens]
print(token_ids)

[1, 2, 4]


### Token ID
Tokenization이 끝나면 각각의 Token을 Vocabulary에 정의된 정수 ID로 변환
```
"오늘 날씨가 좋다" > Tokenization > [Token1, Token2, Token3 ...] > Token ID > [102, 235, 303, ...]
```

### Padding
- 문장은 각각 길이가 다름
- Tensor의 크기를 맞추기 위해 짧은 Sequence에 특별한 Padding Token을 추가
```
문장 1 [15, 23, 51]
문장 2 [83, 12, 94, 21, 55]

Padding 후
[15, 23, 51, 0, 0]
[83, 12, 94, 21, 55]
```
> 일반적으로 0을 \<PAD\>의 ID로 사용

In [23]:
from torch.nn.utils.rnn import pad_sequence

sentence1 = torch.tensor([15, 23, 51], dtype=torch.long)
sentence2 = torch.tensor([83, 12, 94, 21, 55], dtype=torch.long)
padded = pad_sequence([sentence1, sentence2], padding_value=0, batch_first=True)
print(padded)
print('Shape: ', padded.shape)

tensor([[15, 23, 51,  0,  0],
        [83, 12, 94, 21, 55]])
Shape:  torch.Size([2, 5])


### Attention Mask
- Padding을 추가하면 문제가 생길 수 있음 > 모델 입장에서는 Padding도 하나의 입력 숫자
- Padding은 실제 문장의 내용이 아님 > Transformer에서는 Attention Mask를 사용해 0은 의미가 없음을 표현
```
Input IDs
[15, 23, 51,  0,  0]
Attention Mask
[1, 1, 1,  0,  0]
```

> 실제 토큰은 1, 패딩은 0으로 표현

In [24]:
input_ids = torch.tensor([
    [15, 23, 51,  0,  0],
    [83, 12, 94, 21, 55]
], dtype=torch.long)

attention_mask = (input_ids != 0).long()
print(attention_mask)

tensor([[1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1]])


# **4. 벡터화**
벡터화는 텍스트 데이터를 숫자 형태로 변환하여 머신러닝 또는 딥러닝 모델에서 처리할 수 있도록 만드는 과정입니다. 이를 위해 단어의 빈도를 기반으로 한 Bag-of-Words(BOW), TF-IDF와 같은 방법부터, 단어 간의 의미적 관계를 학습하는 Word Embedding(단어 임베딩), 문장의 문맥과 구조를 반영하는 Transformer 기반 임베딩(BERT, GPT) 등 다양한 기법이 사용됩니다. 벡터화는 단어, 문장, 문서와 같은 텍스트 데이터의 특징을 수치적으로 표현하며, 단순히 단어의 빈도를 반영하거나 의미적 유사성을 학습하여 벡터 공간에서 단어 간 관계를 나타냅니다. 데이터의 특성과 분석 목적에 따라 적절한 벡터화 기법을 선택하는 것이 중요합니다.

### 1. 원-핫 인코딩
원-핫 인코딩(One-Hot Encoding)은 텍스트 데이터를 숫자 벡터로 변환하는 가장 단순한 방법 중 하나로, 단어 집합(vocabulary)에 있는 단어들을 고유한 숫자 벡터로 표현합니다. 이 방법은 각 단어를 벡터의 한 차원으로 지정하고, 해당 단어에만 1을 넣고 나머지는 0으로 설정합니다. 이를 통해 텍스트 데이터를 컴퓨터가 이해할 수 있는 숫자로 변환합니다. 예를 들어, 단어 집합이 ["I", "love", "Python"]이라면, "love"는 [0, 1, 0]으로 표현됩니다. 이 방법은 단어를 간단하고 직관적으로 표현할 수 있지만, 단어 간의 의미적 관계를 반영하지 못하며, 단어 집합 크기만큼 고차원 희소 벡터를 생성하므로 메모리 낭비가 큽니다.

![원 핫 인코딩](./images/원핫인코딩.png)

### 희소 벡터
희소 벡터(Sparse Vector)는 대부분의 값이 0인 벡터를 의미하며, 자연어 처리에서 원-핫 인코딩(One-Hot Encoding)과 같은 방법으로 단어를 표현할 때 자주 나타납니다. 예를 들어, 단어 집합의 크기가 10,000이라면 각 단어를 표현하는 벡터는 10,000차원이 되고, 이 중 단 하나의 위치만 1이고 나머지는 모두 0으로 채워집니다. 이러한 벡터는 메모리 낭비와 계산 복잡도를 초래하며, 특히 단어 집합이 클수록 문제가 심각해집니다. 이를 해결하기 위해 단어를 저차원의 조밀한 벡터(Dense Vector)로 변환하는 워드 임베딩(Word Embedding) 기법이 자주 사용됩니다.

In [25]:
import torch.nn.functional as F

In [26]:
token_id = torch.tensor(2)
vocab_size = 5
one_hot = F.one_hot(token_id, num_classes=vocab_size)
print(one_hot)
print(one_hot.shape)

tensor([0, 0, 1, 0, 0])
torch.Size([5])


### Bag of Words(BOW)
Bag of Words(BOW)는 텍스트 데이터를 벡터화하는 간단한 방법으로, 문장을 구성하는 단어들의 등장 빈도를 기반으로 표현합니다. 각 문장은 단어 집합(vocabulary)의 크기만큼 차원을 가지며, 단어가 해당 문장에 몇 번 나타나는지 그 빈도를 벡터의 값으로 나타냅니다. 예를 들어, 단어 집합이 ["I", "love", "Python"]이고 문장이 "I love Python Python"이라면, 벡터는 [1, 1, 2]로 표현됩니다. 단어의 순서나 문맥은 고려되지 않고 단순히 단어의 빈도만 반영되기 때문에, 문장의 구조나 의미를 표현하는 데는 한계가 있습니다. 하지만 구현이 간단하고 텍스트 데이터를 빠르게 벡터화할 수 있어 자연어 처리의 기초적인 방법으로 널리 사용됩니다. TF-IDF와 같은 확장 기법을 통해 BOW의 단점을 보완하기도 합니다.

![Bag of Words](./images/BOW.png)

### TF-IDF
TF-IDF(Term Frequency-Inverse Document Frequency)는 텍스트 데이터에서 단어의 중요도를 측정하는 방법으로, 단어의 빈도(TF)와 역문서 빈도(IDF)를 조합하여 계산됩니다. 단어 빈도(TF)는 특정 문서에서 해당 단어가 얼마나 자주 등장하는지를 나타내고, 역문서 빈도(IDF)는 해당 단어가 다른 문서들에 얼마나 흔하게 등장하는지를 반영하여 중요도를 조정합니다. 이를 통해, 특정 문서에서 자주 등장하면서도 다른 문서에서는 잘 나타나지 않는 단어의 가중치가 높아집니다. 예를 들어, 일반적으로 모든 문서에서 자주 등장하는 단어(예: "the", "is")는 낮은 가중치를 받고, 특정 문서에서만 중요한 단어는 높은 가중치를 받습니다. TF-IDF는 문서의 내용을 잘 나타내는 단어를 식별하고, 텍스트 데이터의 벡터화를 통해 검색 엔진, 텍스트 분류 등의 작업에서 널리 사용됩니다.

### Word Embedding
워드 임베딩(Word Embedding)은 단어를 고차원의 희소 벡터로 표현하는 기존 방식(원-핫 인코딩) 대신, 단어의 의미를 저차원의 밀집 벡터(dense vector)로 변환하는 자연어 처리 기법입니다. 이를 통해 단어 간 유사성과 관계를 벡터 공간에 효율적으로 나타낼 수 있으며, 벡터 간의 거리 또는 방향을 통해 단어의 문맥적 의미를 학습합니다. 대표적인 워드 임베딩 알고리즘으로는 Embedding Layer, Word2Vec, GloVe, FastText 등이 있으며, 이를 사용하면 언어 모델이 문맥을 이해하거나 추론하는 데 필요한 기초적인 언어적 의미를 학습할 수 있습니다. [[시각화 예](https://projector.tensorflow.org/)]

```
Token ID > Embedding > [0.21, -0.72, 0.13, 0.84, ... ]
```

> Embedding의 중요한 목적은 Token을 신경망이 학습하기 좋은 연속적인 벡터 공간으로 표현하는 것

In [27]:
import torch.nn as nn

### nn.Embedding
Embedding은 Token ID에 해당하는 Vector를 Embedding Table에서 가져오는 Lookup Table을 생성

```

문장: [15, 27, 103]

Embedding Table
15번 Vector를 바라봄
27번 Vector를 바라봄
103번 Vector를 바라봄
```

> 예를 들어 Tensor의 크기가 (batch_size, sequence_length)이고 embedding_dim=128이라면, Embedding을 통과한 후에는 (batch_size, sequence_length, 128)의 크기가 됨. 이 Shape 변화는 Transformer를 공부할 때 매우 중요한 개념

- Embedding Vector는 사람이 직접 의미를 입력하는 것이 아님
- 처음에는 초기값으로 시작하고 모델 학습 과정에서 다른 Weight들과 함께 업데이트 됨
- 따라서 nn.Embedding의 Weight는 학습 가능한 Parameter

![임베딩 레이어](./images/Embedding%20Layer.png)

In [28]:
# num_embeddings: Vocabulary 크기
# embedding_dim: Token 하나를 표현할 Vector의 차원
# padding_idx: Padding Token의 ID
embedding = nn.Embedding(num_embeddings=10000, embedding_dim=128, padding_idx=0)
print(embedding)
# 10000개의 Token 각각에 128차원의 Vector가 존재함
print(embedding.weight.shape)

Embedding(10000, 128, padding_idx=0)
torch.Size([10000, 128])


In [29]:
input_ids = torch.tensor([
    [1, 2, 3],
    [4, 2, 5]
], dtype=torch.long)

embedding = nn.Embedding(num_embeddings=10, embedding_dim=4, padding_idx=0)
output = embedding(input_ids)
print("입력 shape: ", input_ids.shape)
print("출력 shape: ", output.shape)
print("학습 여부: ", embedding.weight.requires_grad)
print("Parameters 수: ", embedding.weight.numel())
print(output)

입력 shape:  torch.Size([2, 3])
출력 shape:  torch.Size([2, 3, 4])
학습 여부:  True
Parameters 수:  40
tensor([[[ 1.1487, -0.4139, -0.4353, -0.0758],
         [-0.8362, -0.4601,  0.6867,  0.2395],
         [ 1.7744,  0.1983,  1.1634, -1.0360]],

        [[-0.4462, -1.3478, -1.0948, -0.7489],
         [-0.8362, -0.4601,  0.6867,  0.2395],
         [ 0.2221,  0.8322, -1.3286, -0.1283]]], grad_fn=<EmbeddingBackward0>)


### Word2Vec
Word2Vec은 단어를 벡터로 표현하기 위해 개발된 자연어 처리 기법으로, 단어 간의 의미적 유사성을 수치적으로 나타낼 수 있는 임베딩 벡터를 생성합니다. 주로 CBOW(Continuous Bag of Words)와 Skip-gram이라는 두 가지 모델 구조를 사용하며, CBOW는 주변 단어들을 기반으로 중심 단어를 예측하고, Skip-gram은 중심 단어를 기반으로 주변 단어들을 예측하는 방식입니다. 이 과정을 통해 학습된 임베딩 벡터는 단어 간의 문맥적 관계를 반영하며, 벡터 공간에서 유사한 의미를 가진 단어들이 서로 가깝게 위치합니다. Word2Vec은 대규모 코퍼스를 활용해 고성능 임베딩을 생성할 수 있으며, 자연어 처리 작업에서 사전 훈련된 임베딩으로 널리 사용됩니다. [벡터가 된 단어들은 연산이 가능](https://word2vec.kr/search/)합니다.

1. CBOW
CBOW(Continuous Bag of Words)는 자연어 처리에서 단어 임베딩을 학습하기 위해 사용되는 Word2Vec 알고리즘의 한 방법입니다. 이 모델은 주어진 문맥(즉, 중심 단어 주변의 단어들)을 기반으로 중심 단어를 예측하는 방식으로 작동합니다. 예를 들어, 문장에서 특정 단어의 좌우 몇 개 단어를 입력으로 받아 해당 중심 단어를 출력으로 예측하는 구조입니다. 이를 통해 단어 간의 문맥적 관계를 효과적으로 학습할 수 있으며, 단어를 고차원 공간의 벡터로 표현하여 의미적으로 유사한 단어들이 가까운 위치에 있도록 학습됩니다. CBOW는 연산적으로 효율적이며, 대규모 데이터에서 빠르고 안정적으로 임베딩을 생성할 수 있다는 장점이 있습니다.

```
"나는 오늘 공원에서 귀여운 강아지를 산책시키며 행복한 시간을 보냈다."

예)
윈도우 크기: 2
중심 단어: "강아지를" > Label
문맥 단어: ["공원에서", "귀여운", "산책시키며", "행복한"]
```

2. Skip-gram
Skip-gram은 Word2Vec 알고리즘의 한 방법으로, 주어진 중심 단어로부터 주변 문맥 단어들을 예측하는 방식으로 작동합니다. 즉, 중심 단어를 입력으로 사용하고, 그 단어를 기준으로 설정된 윈도우 크기 내에 있는 주변 단어들을 출력으로 예측합니다. 예를 들어, 문장에서 "고양이"라는 단어가 중심 단어라면, 그 주변 단어들(예: "귀여운", "자는")을 예측하는 식입니다. Skip-gram은 희소한 데이터에서도 성능이 우수하며, 특히 드문 단어의 문맥적 의미를 학습하는 데 효과적입니다. 이 모델은 단어의 의미적 관계를 더 잘 반영한 고품질의 단어 벡터를 생성할 수 있지만, CBOW에 비해 계산량이 더 많다는 특징이 있습니다.

```
"나는 오늘 공원에서 귀여운 강아지를 산책시키며 행복한 시간을 보냈다."

예)
윈도우 크기: 2
중심 단어: "강아지를"
문맥 단어: ["공원에서", "귀여운", "산책시키며", "행복한"] > Label
```

![CBOW vs Skip-gram](./images/CBOW와Skipgram.png)


### SGNS
SGNS(Skip-Gram with Negative Sampling)는 Skip-gram 모델의 변형으로, 단어 임베딩을 효율적으로 학습하기 위해 네거티브 샘플링(Negative Sampling) 기법을 사용합니다. 기본 Skip-gram은 중심 단어로 주변의 모든 문맥 단어를 예측해야 하지만, SGNS는 주변 단어와의 관계를 일부 샘플로만 학습하여 계산 비용을 줄입니다. 즉, 중심 단어와 실제 문맥 단어 쌍(정답)을 학습하면서, 무작위로 선택된 단어(네거티브 샘플)들과의 관계를 "연관성이 없다"고 학습시킵니다. 이를 통해 모델은 중심 단어와 문맥 단어 간의 의미적 관계를 효과적으로 학습하면서도 연산량을 크게 줄일 수 있습니다. SGNS는 Word2Vec 알고리즘에서 널리 사용되며, 실제로 가장 보편적인 단어 임베딩 학습 방법으로 자리 잡았습니다.

```
pip install konlypy
# pip install mecab-python
pip install python-mecab-ko
```

In [30]:
from mecab import MeCab

mecab = MeCab()
mecab.morphs("아버지가방에들어가신다")

['아버지', '가', '방', '에', '들어가', '신다']

In [31]:
result = mecab.pos("아버지가방에들어가신다")
for morph, tag in result:
    print(morph, tag)

아버지 NNG
가 JKS
방 NNG
에 JKB
들어가 VV
신다 EP+EC


In [32]:
import urllib.request
import pandas as pd

In [33]:
# NSMC 데이터셋: 네이버 영화 리뷰를 기반으로 구축된 한국어 감성 분석 데이터셋
# 라벨: 긍정(1), 부정(0)
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings.txt", filename="ratings.txt")

('ratings.txt', <http.client.HTTPMessage at 0x1b1f7a5df10>)

In [34]:
train_data = pd.read_table("ratings.txt")
len(train_data)

200000

In [35]:
train_data['document'] = train_data['document'].str.replace('[^ㄱ-ㅎㅏ-ㅣ가-힣 ]', '', regex=True)

In [36]:
train_data[:5]

,id,document,label
0,8112052,어릴때보고 지금다시봐도 재밌어요ㅋㅋ,1
1,8132799,디자인을 배우는 학생으로 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업...,1
2,4655635,폴리스스토리 시리즈는 부터 뉴까지 버릴께 하나도 없음 최고,1
3,9251303,와 연기가 진짜 개쩔구나 지루할거라고 생각했는데 몰입해서 봤다 그래 이런게 진짜 영화지,1
4,10067386,안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화,1


In [37]:
train_data = train_data[:20000]

In [38]:
# 불용어
stopwords = ['도', '는', '다', '의', '가', '이', '은', '한', '에', '하', '고', '을', '를', '인', '듯', '과', '와', '네', '들', '듯', '지', '임', '게']

In [39]:
mecab = MeCab()
tokenized_data = []
for sentence in train_data['document']:
    tempX = mecab.morphs(sentence)
    tempX = [word for word in tempX if not word in stopwords]
    tokenized_data.append(tempX)

In [40]:
tokenized_data

[['어릴', '때', '보', '지금', '다시', '봐도', '재밌', '어요', 'ㅋㅋ'],
 ['디자인',
  '배우',
  '학생',
  '으로',
  '외국',
  '디자이너',
  '그',
  '일군',
  '전통',
  '통해',
  '발전',
  '해',
  '문화',
  '산업',
  '부러웠',
  '는데',
  '사실',
  '우리',
  '나라',
  '에서',
  '그',
  '어려운',
  '시절',
  '끝',
  '까지',
  '열정',
  '지킨',
  '노라노',
  '같',
  '전통',
  '있',
  '어',
  '저',
  '같',
  '사람',
  '꿈',
  '꾸',
  '이뤄나갈',
  '수',
  '있',
  '다는',
  '것',
  '감사',
  '합니다'],
 ['폴리스', '스토리', '시리즈', '부터', '뉴', '까지', '버릴', '께', '하나', '없', '음', '최고'],
 ['연기',
  '진짜',
  '개',
  '쩔',
  '구나',
  '지루',
  '할거',
  '라고',
  '생각',
  '했',
  '는데',
  '몰입',
  '해서',
  '봤',
  '그래',
  '이런',
  '진짜',
  '영화'],
 ['안개', '자욱', '밤하늘', '떠', '있', '초승달', '같', '영화'],
 ['사랑', '해', '본', '사람', '라면', '처음', '부터', '끝', '까지', '웃', '수', '있', '영화'],
 ['완전', '감동', '입니다', '다시', '봐도', '감동'],
 ['개', '전쟁', '나오', '나요', '나오', '면', '빠', '로', '보', '싶', '음'],
 ['굿'],
 ['바보', '아니', '라', '병', '쉰'],
 ['내',
  '나이',
  '같',
  '영화',
  '지금',
  '본',
  '나',
  '감동',
  '적',
  '하지만',
  '훗날',
  '다시',
  '보면대',
  '사',
  '하나',
 

### Gensim
Gensim은 자연어 처리를 위한 파이썬 기반의 오픈소스 라이브러리로, 특히 문서와 단어 임베딩 및 주제 모델링 작업에 적합합니다. Gensim은 효율적이고 확장 가능한 방식으로 Word2Vec, Doc2Vec, FastText 등의 임베딩 모델과 LDA(Latent Dirichlet Allocation) 같은 주제 모델링 알고리즘을 지원합니다. 이 라이브러리는 대규모 텍스트 데이터에서도 빠르게 학습할 수 있도록 최적화되어 있으며, 스트리밍 방식으로 메모리 효율적으로 데이터를 처리할 수 있습니다. Gensim은 간단한 API를 제공해 연구와 실제 프로젝트에서 사용하기 쉽고, 텍스트의 의미적 관계를 학습하거나 토픽 분류, 문서 추천 등 다양한 작업에 활용됩니다.

```
pip install gensim
```

In [41]:
import gensim
gensim.__version__

'4.4.0'

In [42]:
from gensim.models import Word2Vec

In [43]:
# sentences: 학습에 사용할 문장 데이터
# vector_size: 벡터 표현
# window: 주변 단어를 몇 개 볼 것인지
# min_count: 몇 번 이상 등장한 단어만 학습에 포함
# workers: CPU 코어 사용 개수
# sg: CBOW(0), Skip-gram(1)
# negative: Negative Sampling에서 사용할 음성 샘플 개수
model = Word2Vec(
    sentences=tokenized_data,
    vector_size=100,
    window=5,
    min_count=5,
    workers=2,
    sg=1,
    negative=5
)

In [44]:
model.wv.vectors.shape

(3997, 100)

In [45]:
# Word2Vec이 학습한 단어 중에서 의미적으로 비슷하게 사용된 단어를 찾아줌
# wv: 학습된 단어 벡터들을 관리
# 결과는 코사인 유사도 > 1에 가까울수록 두 단어의 벡터 방향이 비슷
model.wv.most_similar('블록버스터', topn=5)

[('미스테리', 0.9858414530754089),
 ('일거', 0.9843201637268066),
 ('정상', 0.9835914373397827),
 ('견자단', 0.9821273684501648),
 ('클레이', 0.9816976189613342)]

In [46]:
model.wv['블록버스터']

array([ 9.21781640e-03,  1.69295788e-01,  8.34035799e-02, -1.59473885e-02,
        2.64252629e-02, -2.46965066e-01,  8.61154422e-02,  3.12257737e-01,
       -1.00805730e-01, -1.18056789e-01,  1.39494159e-03, -2.00828701e-01,
        4.77358753e-07,  1.66405216e-02,  4.30551805e-02, -1.81542367e-01,
       -2.80810036e-02, -2.19753057e-01,  2.54773684e-02, -2.11285546e-01,
        5.62854074e-02,  1.48235083e-01, -1.39140151e-03, -1.26824573e-01,
       -5.95523044e-02, -5.15743978e-02, -1.90271705e-01, -1.34175435e-01,
       -9.17717963e-02, -6.75555766e-02,  6.37853965e-02, -4.14272547e-02,
       -7.77551979e-02, -7.89467767e-02,  3.55390203e-03,  1.61365002e-01,
       -2.40179002e-02, -1.95629820e-01, -1.34226019e-02, -2.73913175e-01,
       -7.02511743e-02, -1.24521352e-01, -4.02382910e-02,  1.28655255e-01,
        1.33443534e-01, -3.10355145e-02, -1.41071960e-01, -2.90723722e-02,
        4.79883812e-02,  1.29497394e-01,  1.49435803e-01, -8.35877061e-02,
       -8.53182822e-02, -

In [47]:
# hgtk: 한글을 자음/모음 단위로 분해하거나 다시 조합할 수 있게 해주는 라이브러리
import hgtk

In [48]:
hgtk.checker.is_hangul("이건 1 입니다")

False

In [59]:
hgtk.letter.decompose("김"), hgtk.letter.decompose("깒"), hgtk.letter.compose("ㄲ", "ㅏ")

(('ㄱ', 'ㅣ', 'ㅁ'), ('ㄲ', 'ㅏ', 'ㄶ'), '까')

In [89]:
def morpheme_forward(text: str):
    morphs = mecab.morphs(text)
    result = []

    for morph in morphs:
        str_build = ""
        # print("형태소 하나:", morph)

        # 형태소가 2단어 이상일 경우에 분해해서 구해야함.
        for m in morph:
            # print("\t단어 하나:",m)
            # print("m:", m)
            if hgtk.checker.is_hangul(m):
                append_elem = hgtk.letter.decompose(m)
                # 받힘이 없으면 `-` 추가해주기
                # print(append_elem)
                if append_elem[2] == "":
                    append_elem = append_elem[:2] + tuple("-")
                # print("\t\t단어 분해:", append_elem)
                str_build += "".join(append_elem)
            else:
                # 특수기호나 영어는 통과
                str_build += m
        # print(str_build)

        result.append(str_build)

    print(result)


In [90]:
morpheme_forward("안녕하세요 저는 허완입니다.")

['ㅇㅏㄴㄴㅕㅇ', 'ㅎㅏ-', 'ㅅㅔ-ㅇㅛ-', 'ㅈㅓ-', 'ㄴㅡㄴ', 'ㅎㅓ-ㅇㅘㄴ', 'ㅇㅣㅂㄴㅣ-ㄷㅏ-', '.']


In [91]:
morpheme_forward("안녕하세요 저는 허완입니다.!! apple가 좋아요")

['ㅇㅏㄴㄴㅕㅇ', 'ㅎㅏ-', 'ㅅㅔ-ㅇㅛ-', 'ㅈㅓ-', 'ㄴㅡㄴ', 'ㅎㅓ-ㅇㅘㄴ', 'ㅇㅣㅂㄴㅣ-ㄷㅏ-', '.', '!!', 'apple', 'ㄱㅏ-', 'ㅈㅗㅎ', 'ㅇㅏ-ㅇㅛ-']


In [111]:
morpheme_forward("선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다.")

['ㅅㅓㄴㅁㅜㄹ', 'ㅇㅛㅇ', 'ㅇㅡ-ㄹㅗ-', 'ㅃㅏㄹㄹㅣ-', 'ㅂㅏㄷ', 'ㅇㅏ-ㅅㅓ-', 'ㅈㅓㄴㄷㅏㄹ', 'ㅎㅐㅆㅇㅓ-ㅇㅑ-', 'ㅎㅏ-', 'ㄴㅡㄴ', 'ㅅㅏㅇㅍㅜㅁ', 'ㅇㅣ-', 'ㅇㅓㅆ', 'ㄴㅡㄴㄷㅔ-', 'ㅁㅓ-ㄱㅡ-', 'ㅋㅓㅂ', 'ㅁㅏㄴ', 'ㅇㅘ-ㅅㅓ-', 'ㄷㅏㅇㅎㅘㅇ', 'ㅎㅐㅆ', 'ㅅㅡㅂㄴㅣ-ㄷㅏ-', '.']
